---
# Homepage bookmarks.yaml
# Docs: https://gethomepage.dev/configs/bookmarks/
# TODO: Replace with personal bookmarks

- Admin:
    - TrueNAS:
        - abbr: TN
          href: http://the-library.tail227692.ts.net
    - Tailscale:
        - abbr: TS
          href: https://login.tailscale.com/admin
    - Router:
        - abbr: RT
          href: http://192.168.1.1
